In [2]:
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

In [3]:
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from scipy import stats
from sklearn import preprocessing
from sklearn.decomposition import PCA

In [4]:
new_articles = pd.read_json("D:\\APP\\NITW\\Machine Learning\\\Assignment-7\\NewsArticles.json")

In [146]:
new_articles.head()

Article  \
0    Musical treatment for Capra film\n\nThe classi...   
1    Spark heads world Booker list\n\nDame Muriel S...   
10   Artists' secret postcards on sale\n\nPostcards...   
100  Chepkemei joins Edinburgh line-up\n\nSusan Che...   
101  El Guerrouj targets cross country\n\nDouble Ol...   

                                  Preprocessed-Article  \
0    Musical treatment Capra film The classic film ...   
1    Spark heads world Booker list Dame Muriel Spar...   
10   Artists  secret postcards sale Postcards artis...   
100  Chepkemei joins Edinburgh lineup Susan Chepkem...   
101  El Guerrouj targets cross country Double Olymp...   

                                                Vector  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
10   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
100  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
101  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [6]:
new_articles.describe()

Article  \
count                                                 179   
unique                                                177   
top     Edwards tips Idowu for Euro gold\n\nWorld outd...   
freq                                                    2   

                                     Preprocessed-Article  \
count                                                 179   
unique                                                177   
top     Edwards tips Idowu Euro gold World outdoor tri...   
freq                                                    2   

                                                   Vector  
count                                                 179  
unique                                                177  
top     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
freq                                                    2

In [7]:
new_articles.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 179 entries, 0 to 99
Data columns (total 3 columns):
Article                 179 non-null object
Preprocessed-Article    179 non-null object
Vector                  179 non-null object
dtypes: object(3)
memory usage: 5.6+ KB


In [40]:
#copy_new_articles = new_articles
#Transsform the Vector to dummies
#copy_new_articles = pd.get_dummies(copy_new_articles, columns=['Preprocessed-Article'])
#le = preprocessing.LabelEncoder()
#le.fit(copy_new_articles[['Preprocessed-Article']])
#numeric_article = le.transform(copy_new_articles[['Preprocessed-Article']])
#Kmeans_model = KMeans(n_clusters=3).fit(numeric_article.reshape(-1, 1))
#labels = Kmeans_model.predict(numeric_article.reshape(-1, 1))
#centroids = Kmeans_model.cluster_centers_
#sse = Kmeans_model.inertia_
#print(sse)
#pca = PCA(n_components = 1) 
  
#numeric_article_pca = pca.fit_transform(numeric_article.reshape(-1, 1))
#pca_Kmeans_model = KMeans(n_clusters=3).fit(numeric_article_pca)
#pca_sse = pca_Kmeans_model.inertia_
#print(pca_sse)

In [32]:
article_vectors = new_articles['Vector']
article_vectors_array = np.array(article_vectors)

In [61]:
print(article_vectors_array)
#print("nsamples: "+ nsamples+ ", nx: "+ nx+ ", ny: "+ ny)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [102]:
Kmeans_model = KMeans(n_clusters=5).fit(np.asarray(article_vectors_array[0]).reshape(-1, 1))

In [35]:
#labels = Kmeans_model.predict(np.asarray(article_vectors_array[0]).reshape(-1, 1))

In [103]:
sse = Kmeans_model.inertia_
print(sse)

0.022997761550314723


In [104]:
print(Kmeans_model.cluster_centers_)

[[8.32667268e-17]
 [9.87266467e-02]
 [3.96384489e-01]
 [1.88766740e-01]
 [5.97069683e-02]]


In [161]:
labels = Kmeans_model.labels_
#print(labels)
count = np.bincount(labels[labels>0])
print(count)
print(np.max(count))
top_label = list(count).index(np.max(count)) + 1
print(top_label)

[ 0 19  2  8 54]
54
5


In [163]:
pca = PCA(n_components = 100)

In [164]:
article_vectors_array_pca = pca.fit_transform(np.asarray(article_vectors_array[0]).reshape(-1, 1))
#print(article_vectors_array_pca)

ValueError: n_components=100 must be between 0 and min(n_samples, n_features)=1 with svd_solver='full'

In [122]:
pca_Kmeans_model = KMeans(n_clusters=5).fit(np.asarray(article_vectors_array_pca).reshape(-1, 1))

In [123]:
pca_sse = pca_Kmeans_model.inertia_
print(pca_sse)

0.023053222244152044


In [124]:
print(pca_Kmeans_model.cluster_centers_)

[[-0.00083479]
 [ 0.19403021]
 [ 0.05963906]
 [ 0.3955497 ]
 [ 0.10247222]]


In [162]:
pca_labels = pca_Kmeans_model.labels_
#print(pca_labels)
pca_count = np.bincount(pca_labels[pca_labels > 0])
print(pca_count)
print(np.max(pca_count))
pca_top_label = list(pca_count).index(np.max(pca_count)) + 1
print(pca_top_label)

[ 0  7 56  2 18]
56
3
